openapi: 3.0.3
info:
  title: Swagger CRM - Private API
  version: 1.0.0
servers:
  - url: https://cms-back-3ykd.onrender.com/api
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: 'Login endpoint'
      description: 'Send email and password object to endpoint for login. 
      {
        email: value,
        password: value
      }'
      operationId: ''
      responses:
        '200':
          description: '{ accessToken: String refreshToken: String user: email: example@gmail.com id:  }'
        '401':
          description: 'message: "Wrong password"'
        '404':
          description: 'message: "User with this email was not found"'
  /registration:
    post:
      tags:
        - Authentication
      summary: 'Registration endpoint'
      description: 'Send email and password object to endpoint for registration. (email type is email , password min length 4 , max 1000) 
      {
        email: value,
        password: value
      }'
      operationId: ''
      responses:
        '200':
          description: '{ accessToken: String, refreshToken: String, user: email: example@gmail.com id: 1 }'
        '409':
          description: 'message: "An account is already registered with this email"'
  /logout:
    post:
      tags:
        - Authentication
      summary: 'Logout endpoint'
      description: 'Send'
      operationId: ''
      responses:
        '200':
          description: 'message: "You have been successfully logged out!"'
        '201':
          description: 'message: "You are already logged out!"'
  /refresh:
    get:
      tags:
        - Authentication
      summary: 'Refresh token endpoint'
      description: 'Send get reques for refresh your token , backend read your token from your readonly cookie.'
      operationId: ''
      responses:
        '200':
          description: '{ accessToken: String, refreshToken: String, user: email: example@gmail.com id: 1 }'